"""add two indexes to pull_requests

Revision ID: 3f138d51442c
Revises: 8ef9b7227965
Create Date: 2021-08-15 15:25:04.176696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f138d51442c'
down_revision = '8ef9b7227965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
