"""change comment_or_not to default=0 and not nullable and add unique index for unique pull_request

Revision ID: 4939a95bd8e1
Revises: ec616b7d4340
Create Date: 2021-08-15 15:50:55.855430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4939a95bd8e1'
down_revision = 'ec616b7d4340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pull_requests', 'comment_or_not',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_index('owner_repo_num', 'pull_requests', ['owner_login', 'repo_name', 'number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('owner_repo_num', table_name='pull_requests')
    op.alter_column('pull_requests', 'comment_or_not',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
