"""add locked column to pull_requests table

Revision ID: 4ad7b4a06e6c
Revises: 5c2ce5113df2
Create Date: 2021-08-14 15:21:25.387604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad7b4a06e6c'
down_revision = '5c2ce5113df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'locked')
    # ### end Alembic commands ###
