"""add column installation_id to pull_requests

Revision ID: 8ef9b7227965
Revises: e69e7db9d798
Create Date: 2021-08-15 15:21:53.401153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef9b7227965'
down_revision = 'e69e7db9d798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('installation_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'installation_id')
    # ### end Alembic commands ###
