"""change table pull_requests

Revision ID: e69e7db9d798
Revises: 4ad7b4a06e6c
Create Date: 2021-08-15 13:15:50.974380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e69e7db9d798'
down_revision = '4ad7b4a06e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('last_comment_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('pull_requests', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('pull_requests', 'last_comment_at')
    # ### end Alembic commands ###
