"""change index format

Revision ID: ec616b7d4340
Revises: f076c766cb48
Create Date: 2021-08-15 15:30:23.121589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec616b7d4340'
down_revision = 'f076c766cb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_pull_request_id'), 'comments', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_locked'), 'pull_requests', ['locked'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_locked'), table_name='pull_requests')
    op.drop_index(op.f('ix_comments_pull_request_id'), table_name='comments')
    # ### end Alembic commands ###
