"""add an index to comments

Revision ID: f076c766cb48
Revises: 3f138d51442c
Create Date: 2021-08-15 15:25:58.162771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f076c766cb48'
down_revision = '3f138d51442c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
